const ON_USER_DETAILS_FETCHED = 'ON_USER_DETAILS_FETCHED'
const ON_USER_DETAILS_FETCHED_ERROR = 'ON_USER_DETAILS_FETCHED_ERROR'

export default {
  ON_USER_DETAILS_FETCHED,
  ON_USER_DETAILS_FETCHED_ERROR,
}
